image: node:latest

stages:
  - lint
  - validate
  - push-to-github
  - publish

lint_check:
  stage: lint
  script:
    # TODO: lint process
    - echo "Lint is not running yet"

validate:
  stage: validate
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  script:
    - |
      # Install jq to parse package.json
      apt-get update -qy
      apt-get install -y jq

      # Extract version from package.json
      PACKAGE_VERSION=$(jq -r .version package.json)
      
      # Compare the tag version with the package version
      if [ "$CI_COMMIT_TAG" != "v$PACKAGE_VERSION" ]; then
        echo "Error: Tag version ($CI_COMMIT_TAG) does not match package version ($PACKAGE_VERSION)";
        exit 1;
      else
        echo "Tag version matches package version";
      fi

push_tag_to_github:
  stage: push-to-github
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  variables:
    GIT_STRATEGY: clone
  script:
    - |
      # Setup GitHub permissions
      echo "${GITHUB_PEM_FILE}" > github-private-key.pem
      yarn global add github-app-installation-token 
      GITHUB_TOKEN=$(github-app-installation-token --appId ${GITHUB_APP_ID} --installationId ${GITHUB_INSTALLATION_ID} --privateKeyLocation github-private-key.pem)
      
      # push tag to GitHub
      git remote add github https://github.com/Harbor-Lockers/harbor-react-native-sdk.git
      git remote set-url github "https://git:${GITHUB_TOKEN}@github.com/Harbor-Lockers/harbor-react-native-sdk.git"
      git fetch github
      git push github "$CI_COMMIT_TAG"

npm_publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --access=public
