image: node:latest

stages:
  - validate
  - push-to-github
  - publish

validate:
  stage: validate
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+(-beta\.[0-9]+)?$/'
  script:
    - |
      node -v
      yarn -v
      # Install jq to parse package.json
      apt-get update -qy
      apt-get install -y jq

      # Extract version from package.json
      PACKAGE_VERSION=$(jq -r .version package.json)
      
      # Compare the tag version with the package version
      if [ "$CI_COMMIT_TAG" != "$PACKAGE_VERSION" ]; then
        echo "Error: Tag version ($CI_COMMIT_TAG) does not match package version ($PACKAGE_VERSION)";
        exit 1;
      else
        echo "Tag version matches package version";
      fi

.default_push_to_github:
  variables:
    GIT_STRATEGY: clone
  before_script:
    - node -v
    - yarn -v
    - echo "${GITHUB_PEM_FILE}" > github-private-key.pem
    - npm install -g github-app-installation-token
    - GITHUB_TOKEN=$(github-app-installation-token --appId ${GITHUB_APP_ID} --installationId ${GITHUB_INSTALLATION_ID} --privateKeyLocation github-private-key.pem)
    - git remote add github https://github.com/Harbor-Lockers/harbor-react-native-sdk.git
    - git remote set-url github "https://git:${GITHUB_TOKEN}@github.com/Harbor-Lockers/harbor-react-native-sdk.git"
    - git fetch github

push_tag_to_github:
  stage: push-to-github
  extends: .default_push_to_github
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+(-beta\.[0-9]+)?$/'
  script:
    - git push github "$CI_COMMIT_TAG"

push_to_github_master:
  stage: push-to-github
  extends: .default_push_to_github
  only:
    - master
  script:
    - git push github HEAD:refs/heads/master

npm_publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+(-beta\.[0-9]+)?$/'
  script:
    - node -v
    - yarn -v
    - yarn install --immutable
    - yarn config set npmAuthToken "$NPM_TOKEN"
    - yarn npm publish --access=public
